txtOwnerId: "hq-dev-eks-cluster"

# Limits ExternalDNS to only touch dev records
domainFilter:
  - dev.sctp-sandbox.com  # Change to your exact dev domain/subdomain

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::255945442255:role/hq-dev-EKSExternalDNSRole"