txtOwnerId: "mine-prod-eks-cluster"

# Limits ExternalDNS to only touch prod records
domainFilter:
  - sctp-sandbox.com      # Change to your production domain

# REMOVED: serviceAccount annotations block deleted here 
# because your GitHub Actions Pipeline injects this dynamically!
#serviceAccount:
#  annotations:
#    eks.amazonaws.com/role-arn: "arn:aws:iam::255945442255:role/hq-prod-EKSExternalDNSRole" # Your prod IAM role