provider: aws
sources:                                 # Instructs ExternalDNS to watch both standard LoadBalancer Services and Ingress routes
  - service
  - ingress
aws:
  region: ap-southeast-1 
  zoneType: public  

policy: sync                             # Automatically creates AND deletes records when apps are removed
registry: txt
txtOwnerId: "mightycapstone-eks-cluster" # Tracks ownership of records in Route 53

serviceAccount:
  create: true
  name: external-dns
  automountServiceAccountToken: true # <-- Fixes the token mounting issue globally
